###
# migrate and collect static for Django App
###


# Django collectstatic
- name: Django Collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{app_dir}}"
    virtualenv: "{{ venv_dir }}"


#- name: migrate the db
- name: Run Django database migrations
  django_manage:
    command: makemigrations
    app_path: "{{ app_dir }}"
    virtualenv: "{{ venv_dir }}"


#- name: migrate the db
- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ app_dir }}"
    virtualenv: "{{ venv_dir }}"


## Create an initial superuser.
#- django_manage:
#    command: "createsuperuser --noinput --username=cincypy --email=cincypy@gmail.com"
#    app_path: "{{ app_dir }}"
#    virtualenv: "{{ venv_dir }}"